// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV9XOEC_91zYb8hPallwqEqKVw2mrbwvY',
    appId: '1:117995460074:web:33941d136f0798fd5e8e93',
    messagingSenderId: '117995460074',
    projectId: 'bitebuddies-61eeb',
    authDomain: 'bitebuddies-61eeb.firebaseapp.com',
    storageBucket: 'bitebuddies-61eeb.appspot.com',
    measurementId: 'G-8VNBL7JD75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZXCOXmpgMwe5mJjsG9ou2fhksud22tq4',
    appId: '1:117995460074:android:b52b322abb92b6065e8e93',
    messagingSenderId: '117995460074',
    projectId: 'bitebuddies-61eeb',
    storageBucket: 'bitebuddies-61eeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE5VRLHtBJyl_B_erk5PUif_9QmsAXmtI',
    appId: '1:117995460074:ios:5e69f8c6c5d640ad5e8e93',
    messagingSenderId: '117995460074',
    projectId: 'bitebuddies-61eeb',
    storageBucket: 'bitebuddies-61eeb.appspot.com',
    iosClientId: '117995460074-q9akgv1vei2in1rpemmf9ce955s4afc9.apps.googleusercontent.com',
    iosBundleId: 'com.example.monkeyAppDemo',
  );
}
